/**
 * Bootstrap a steward workspace: a fresh git repo with the first persistent
 * trading-agent scaffold. Cross-platform Node, run by the Electron-bundled
 * Node and bundled git via `_common.mjs`.
 *
 * Context injection writes AGENTS.md / CLAUDE.md, CLI skills, and the final
 * context manifest after this script returns. This script owns only the
 * workspace-local steward file layout.
 *
 *   argv: process.argv[2] = tag, process.argv[3] = outDir
 *   env:  AQ_TEMPLATE_ROOT - abs path to this template's root
 */

import { mkdirSync, writeFileSync } from 'node:fs'
import { join } from 'node:path'
import { initWorkspaceDir, copyReadme, setupGitExcludes, git } from '../_common.mjs'

const tag = process.argv[2]
const outDir = process.argv[3]
if (!tag || !outDir) {
  console.error('usage: bootstrap.mjs <tag> <outDir>')
  process.exit(1)
}

const stewardReadme = `# Steward Workspace

This directory is the steward's structured trading context. A steward wake is
not a general coding request; it is a narrow trading decision envelope that must
end with one JSON line in ledger/decisions.jsonl.

## Files

- config.json: steward defaults, session pointer, account placeholder, and
  cost budget assumptions.
- context-manifest.json: generated by OpenAlice context injection after root
  instructions and skills are written.
- wakes/<wakeId>.json: one structured input envelope per wake.
- ledger/decisions.jsonl: one structured decision/completion marker per wake.
- validate-ledger.mjs: local schema sanity check for one wake's ledger marker,
  plus an integrity cross-check that every already-completed wake still has its
  ledger entry (a prior completed decision must never silently disappear). It is
  also the COMMIT POINT: on success it publishes a finalization marker in
  finalize/, and the supervisor completes the wake only after that marker
  matches the current entry. If you edit the ledger line afterward, re-run it.
- finalize/: gitignored per-wake finalization markers (the write-then-validate
  commit barrier). You do not edit these; validate-ledger.mjs writes them.
- tmp/: gitignored scratch space for --json-file payloads (order/commit/reject
  free-text fields written here via the Write tool, then passed to alice-uta
  by path — never embedded in a Bash argument).

## First action on wake

Read the wake file named by the injected wake message, then run the fixed UTA
checklist: account, positions, open orders, risk, market, and history. Decide
no_trade, propose_trade, or blocked. Append exactly one ledger JSON object.

Do not inspect OpenAlice source code. Do not call push. Do not end a wake
without a ledger entry.
`

const validateLedger = `#!/usr/bin/env node
const wakeId = process.argv[2]
if (!wakeId) fail('usage: node .alice/steward/validate-ledger.mjs <wakeId>')

const fs = await import('node:fs/promises')
const path = '.alice/steward/ledger/decisions.jsonl'
let raw = ''
try {
  raw = await fs.readFile(path, 'utf8')
} catch (err) {
  fail('cannot read ' + path + ': ' + err.message)
}

// Issue #139: bind finalization to the EXTERNALLY-known active wake, not the id
// the ledger entry asserts about itself. The wake record file under wakes/ is
// written by the server when the wake is posted; require one for <wakeId> that
// is still non-terminal. This refuses to "finalize" a phantom/typo id (no wake
// record) or re-finalize an already-completed wake (replay) -- exactly how a
// copied-suffix wakeId slipped through: it had no active wake behind it. Run
// this with the EXACT wakeId from the wake message; never invent or copy one.
const terminalStatuses = ['done', 'blocked', 'error', 'timeout', 'stuck']
let wakeRecord
try {
  wakeRecord = JSON.parse(await fs.readFile('.alice/steward/wakes/' + encodeURIComponent(wakeId) + '.json', 'utf8'))
} catch (err) {
  if (err && err.code === 'ENOENT') fail('no active posted wake "' + wakeId + '" (no wake record under .alice/steward/wakes/) -- validate with the exact wakeId from the wake message; do not invent or copy a prior wake id')
  fail('cannot read wake record for "' + wakeId + '": ' + err.message)
}
if (wakeRecord && terminalStatuses.includes(wakeRecord.status)) fail('wake "' + wakeId + '" is already ' + wakeRecord.status + '; a completed wake cannot be re-finalized -- finalize only the active posted wake')

const requiredTopLevel = [
  'version',
  'wakeId',
  'at',
  'accountId',
  'decision',
  'status',
  'completion',
  'checklist',
  'thesis',
  'actions',
  'pendingHash',
  'invalidation',
  'cost',
]
const requiredChecklist = ['account', 'positions', 'orders', 'risk', 'market', 'history']
const requiredCost = [
  'model',
  'inputTokens',
  'outputTokens',
  'modelCostUsd',
  'allocatedServerCostUsd',
  'tradingFeesUsd',
  'estimatedSlippageUsd',
  'totalEstimatedCostUsd',
]
const actionKinds = ['order_place', 'order_commit', 'order_modify', 'order_cancel', 'position_close', 'git_reject']
const actionOutcomes = ['executed', 'awaiting_approval', 'policy_denied', 'failed']

const lines = raw.split('\\n').map((line) => line.trim()).filter(Boolean)
const matches = []
for (let i = 0; i < lines.length; i++) {
  let parsed
  try {
    parsed = JSON.parse(lines[i])
  } catch (err) {
    if (lines[i].includes(wakeId)) fail('ledger line ' + (i + 1) + ' mentions this wake but is invalid JSON: ' + err.message)
    continue
  }
  if (parsed && parsed.wakeId === wakeId) matches.push({ line: i + 1, entry: parsed })
}
if (matches.length === 0) fail('no ledger entry found for wake ' + wakeId)
// Issue #125 D3: exactly one terminal entry per wakeId, first-wins. A later
// duplicate can never alter the recorded decision -- appending a second entry
// for the same wake is a validation error, not a revision.
if (matches.length > 1) fail('wake ' + wakeId + ' has ' + matches.length + ' ledger entries (lines ' + matches.map((m) => m.line).join(', ') + '); exactly one is allowed (first-wins). Fix the earlier entry in place; do not append a second.')

const found = matches[0]
const entry = found.entry
const missing = requiredTopLevel.filter((key) => !(key in entry))
if (missing.length) fail('line ' + found.line + ' is missing top-level field(s): ' + missing.join(', '))
if (entry.version !== 2) fail('line ' + found.line + ' version must be 2')
if (!['no_trade', 'propose_trade', 'blocked'].includes(entry.decision)) fail('line ' + found.line + ' has invalid decision')
if (!['done', 'blocked', 'error'].includes(entry.status)) fail('line ' + found.line + ' has invalid status')
if (!entry.completion || typeof entry.completion !== 'object' || Array.isArray(entry.completion)) fail('line ' + found.line + ' completion must be an object')
if (typeof entry.completion.reason !== 'string' || !entry.completion.reason.trim()) fail('line ' + found.line + ' completion.reason is required')
if (!Array.isArray(entry.completion.evidenceRefs) || entry.completion.evidenceRefs.length === 0) fail('line ' + found.line + ' completion.evidenceRefs must be a non-empty array')
// Issue #139: the wake: evidence self-reference must name exactly this entry's
// own top-level wakeId. A steward was seen copying a prior wake's UUID suffix
// into the top-level wakeId while its evidence still referenced the real active
// wake -- an internally contradictory entry that finalized a phantom id.
const evWakeRefs = entry.completion.evidenceRefs.filter((r) => typeof r === 'string' && r.indexOf('wake:') === 0).map((r) => r.slice(5))
if (evWakeRefs.indexOf(entry.wakeId) === -1) fail('line ' + found.line + ' completion.evidenceRefs must include the self-reference "wake:' + entry.wakeId + '" matching the top-level wakeId')
for (let r = 0; r < evWakeRefs.length; r++) {
  if (evWakeRefs[r] !== entry.wakeId) fail('line ' + found.line + ' completion.evidenceRefs references a different wake (' + evWakeRefs[r] + ') than the top-level wakeId (' + entry.wakeId + '); a copied or contradictory wake id is invalid -- fix the top-level wakeId to match the posted wake')
}
if (!entry.checklist || typeof entry.checklist !== 'object' || Array.isArray(entry.checklist)) fail('line ' + found.line + ' checklist must be a TOP-LEVEL object, not nested inside completion')
const missingChecklist = requiredChecklist.filter((key) => typeof entry.checklist[key] !== 'string' || !entry.checklist[key])
if (missingChecklist.length) fail('line ' + found.line + ' checklist is missing field(s): ' + missingChecklist.join(', '))
if (!Array.isArray(entry.actions)) fail('line ' + found.line + ' actions must be an array')

// Issue #125 D2: v2 actions are typed objects, never free-text strings. Each
// action records kind, the exact aliceId (except git_reject), a params summary,
// commitHash where applicable, and the real guard/broker outcome.
let anyExecuted = false
for (let a = 0; a < entry.actions.length; a++) {
  const action = entry.actions[a]
  const where = 'line ' + found.line + ' actions[' + a + ']'
  if (!action || typeof action !== 'object' || Array.isArray(action)) fail(where + ' must be an object -- free-text action strings are rejected at v2')
  if (!actionKinds.includes(action.kind)) fail(where + ' has invalid kind: ' + JSON.stringify(action.kind) + '; expected one of ' + actionKinds.join(', '))
  if (!action.params || typeof action.params !== 'object' || Array.isArray(action.params)) fail(where + ' params must be an object summary')
  if (!actionOutcomes.includes(action.outcome)) fail(where + ' has invalid outcome: ' + JSON.stringify(action.outcome) + '; expected one of ' + actionOutcomes.join(', '))
  if (action.kind !== 'git_reject' && (typeof action.aliceId !== 'string' || !action.aliceId)) fail(where + ' requires a non-empty aliceId')
  if (action.outcome === 'policy_denied' && (!Array.isArray(action.violations) || action.violations.length === 0)) fail(where + ' is policy_denied and must record non-empty violations')
  if (action.outcome === 'executed' && action.kind !== 'git_reject' && (typeof action.commitHash !== 'string' || !action.commitHash)) fail(where + ' is executed and must record its commitHash')
  if (action.outcome === 'executed') anyExecuted = true
}

// Issue #125 D1: pendingHash is strictly the stage currently awaiting approval,
// or null. Once any action executed (auto-pushed), it MUST be null -- the
// commit hash lives in actions[].commitHash, not here.
if (entry.pendingHash !== null && typeof entry.pendingHash !== 'string') fail('line ' + found.line + ' pendingHash must be string or null')
if (anyExecuted && entry.pendingHash !== null) fail('line ' + found.line + ' pendingHash must be null once an action has outcome "executed" (put the commit hash in actions[].commitHash)')
if (!entry.cost || typeof entry.cost !== 'object' || Array.isArray(entry.cost)) fail('line ' + found.line + ' cost must be an object')
const missingCost = requiredCost.filter((key) => !(key in entry.cost))
if (missingCost.length) fail('line ' + found.line + ' cost is missing field(s): ' + missingCost.join(', '))

// Issue #134: ledger-integrity cross-check (corruption-evident, not tamper-
// proof -- wake/ledger/receipt share one agent-writable trust domain). A wake
// that ALREADY reached a ledger-backed terminal state (done|blocked|error) AND
// was dispatched must still have its first-wins ledger entry, unchanged.
// Compare every such terminal wake record against the current ledger, so
// validating THIS wake fails if an earlier completed decision disappeared or
// was mutated -- exactly what happened when the persistent session deleted and
// rebuilt decisions.jsonl mid-run. The semantic projection + canonical
// fingerprint mirror src/workspaces/steward/ledger-receipt.ts byte for byte (a
// pinned golden vector guards the parity); keep them in lockstep. First-wins
// selection is the first JSON-parseable object line per wakeId (schema-
// independent), matching the supervisor. timeout/stuck wakes, and wakes that
// never dispatched (no injectedAt and no receipt), write no ledger entry and
// are skipped.
const { createHash } = await import('node:crypto')
const LEDGER_SEMANTIC_KEYS = ['version', 'wakeId', 'at', 'accountId', 'decision', 'status', 'context', 'completion', 'checklist', 'thesis', 'actions', 'pendingHash', 'invalidation', 'cost']
function canonicalize(value) {
  if (Array.isArray(value)) return value.map(canonicalize)
  if (value && typeof value === 'object') {
    const out = {}
    for (const key of Object.keys(value).sort()) out[key] = canonicalize(value[key])
    return out
  }
  return value
}
function semanticProjection(obj) {
  const source = obj && typeof obj === 'object' ? obj : {}
  const out = {}
  for (const key of LEDGER_SEMANTIC_KEYS) if (key in source) out[key] = source[key]
  return out
}
function ledgerFingerprint(obj) {
  return createHash('sha256').update(JSON.stringify(canonicalize(semanticProjection(obj)))).digest('hex')
}
const firstWins = new Map()
for (let i = 0; i < lines.length; i++) {
  let p
  try { p = JSON.parse(lines[i]) } catch { continue }
  if (p && typeof p === 'object' && typeof p.wakeId === 'string' && !firstWins.has(p.wakeId)) firstWins.set(p.wakeId, p)
}
const wakesDir = '.alice/steward/wakes'
let wakeFiles = []
try {
  wakeFiles = (await fs.readdir(wakesDir)).filter((n) => n.endsWith('.json'))
} catch (err) {
  if (err.code !== 'ENOENT') fail('cannot read ' + wakesDir + ': ' + err.message)
}
const terminalBacked = ['done', 'blocked', 'error']
for (const name of wakeFiles) {
  let rec
  try {
    rec = JSON.parse(await fs.readFile(wakesDir + '/' + name, 'utf8'))
  } catch (err) {
    fail('wake record ' + name + ' is invalid JSON: ' + err.message)
  }
  if (!rec || typeof rec !== 'object' || !terminalBacked.includes(rec.status)) continue
  // Skip a wake that never actually dispatched (no injectedAt and no receipt):
  // a POST-time failure marked terminal was never ledger-backed.
  if (!rec.injectedAt && !rec.ledgerReceipt) continue
  const priorEntry = firstWins.get(rec.wakeId)
  if (!priorEntry) fail('terminal wake ' + rec.wakeId + ' (status ' + rec.status + ') has no ledger entry -- an earlier completed decision disappeared from ' + path)
  if (rec.ledgerReceipt && typeof rec.ledgerReceipt.fingerprint === 'string') {
    const fp = ledgerFingerprint(priorEntry)
    if (fp !== rec.ledgerReceipt.fingerprint) fail('terminal wake ' + rec.wakeId + ' ledger entry changed since it was recorded (fingerprint mismatch) -- ledger history was mutated in place')
  }
}

// Issue #136 finalize barrier: every check above passed -- this wake's entry is
// strict v2, unique (no duplicate), and every prior terminal wake is still
// intact. Validation is the COMMIT POINT: atomically publish the finalization
// marker the supervisor waits for before it terminalizes this wake and captures
// its receipt. A later same-wake correction re-runs this validator, which
// atomically REPLACES the marker with the corrected fingerprint. If any check
// above had failed we would have exited already, so no marker is written for a
// failing entry. tmp+rename keeps a concurrent reader from seeing a partial
// file, and encodeURIComponent keeps an arbitrary wakeId path-safe.
const finalizeDir = '.alice/steward/finalize'
await fs.mkdir(finalizeDir, { recursive: true })
const markerPath = finalizeDir + '/' + encodeURIComponent(wakeId) + '.json'
const marker = {
  version: 1,
  wakeId,
  fingerprint: ledgerFingerprint(entry),
  validatedAt: new Date().toISOString(),
  schemaVersion: entry.version,
}
const tmpMarker = markerPath + '.tmp'
await fs.writeFile(tmpMarker, JSON.stringify(marker, null, 2) + '\\n', 'utf8')
await fs.rename(tmpMarker, markerPath)

console.log('ok: ledger entry for ' + wakeId + ' validates at line ' + found.line + '; finalization marker published')

function fail(message) {
  console.error('validate-ledger: ' + message)
  process.exit(1)
}
`

const config = {
  version: 1,
  agent: 'codex',
  sessionId: null,
  accountId: null,
  monthlyBudget: {
    modelUsd: 200,
    serverUsd: 50,
  },
  costPolicy: {
    warnAtPct: 80,
    blockAtPct: 100,
  },
}

initWorkspaceDir(outDir)
copyReadme(outDir)

await git(['init', '-q'], outDir)
setupGitExcludes(
  outDir,
  '.alice/steward/state.json',
  '.alice/steward/locks/',
  '.alice/steward/supervisor.jsonl',
  '.alice/steward/tmp/',
  '.alice/steward/finalize/',
)

const stewardRoot = join(outDir, '.alice', 'steward')
mkdirSync(join(stewardRoot, 'wakes'), { recursive: true })
mkdirSync(join(stewardRoot, 'ledger'), { recursive: true })
mkdirSync(join(stewardRoot, 'locks'), { recursive: true })
mkdirSync(join(stewardRoot, 'tmp'), { recursive: true })
mkdirSync(join(stewardRoot, 'finalize'), { recursive: true })

writeFileSync(join(stewardRoot, 'README.md'), stewardReadme)
writeFileSync(join(stewardRoot, 'config.json'), `${JSON.stringify(config, null, 2)}\n`)
writeFileSync(join(stewardRoot, 'validate-ledger.mjs'), validateLedger)
writeFileSync(join(stewardRoot, 'wakes', '.gitkeep'), '')
writeFileSync(join(stewardRoot, 'ledger', 'decisions.jsonl'), '')
writeFileSync(join(stewardRoot, 'supervisor.jsonl'), '')

console.log(`bootstrapped steward workspace '${tag}' at ${outDir}`)
