/**
 * Bootstrap a steward workspace: a fresh git repo with the first persistent
 * trading-agent scaffold. Cross-platform Node, run by the Electron-bundled
 * Node and bundled git via `_common.mjs`.
 *
 * Context injection writes AGENTS.md / CLAUDE.md, CLI skills, and the final
 * context manifest after this script returns. This script owns only the
 * workspace-local steward file layout.
 *
 *   create:  argv[2] = tag,               argv[3] = outDir (new workspace)
 *   refresh: argv[2] = '--refresh-runtime', argv[3] = existing workspaceDir
 *   env:     AQ_TEMPLATE_ROOT - abs path to this template's root
 *
 * Issue #140 merge gate: an EXISTING persistent steward workspace is never
 * re-bootstrapped, but the injector now emits the new draft-based wake
 * instruction. `--refresh-runtime` idempotently updates ONLY the launcher-owned
 * operational artifacts (validate-ledger.mjs, .alice/steward/README.md, the
 * runtime-protocol marker, the operational dirs, and the git excludes) via
 * same-dir atomic replace — it never inits a repo and never touches user content
 * (config.json, wakes/, ledger/decisions.jsonl, finalize/ markers, drafts/).
 */

import { mkdirSync, writeFileSync, readFileSync, renameSync, appendFileSync, existsSync } from 'node:fs'
import { join } from 'node:path'
import { initWorkspaceDir, copyReadme, setupGitExcludes, git } from '../_common.mjs'

const tag = process.argv[2]
const outDir = process.argv[3]
if (!tag || !outDir) {
  console.error('usage: bootstrap.mjs <tag> <outDir>   |   bootstrap.mjs --refresh-runtime <workspaceDir>')
  process.exit(1)
}
const REFRESH_MODE = tag === '--refresh-runtime'

/** The draft-based ledger runtime protocol (issue #140). Bumped when the
 *  launcher-owned validator/dir contract changes so a refresh is detectable. */
const STEWARD_RUNTIME_PROTOCOL = 2
/** Operational subdirs the launcher owns (created idempotently). */
const STEWARD_RUNTIME_DIRS = ['wakes', 'ledger', 'locks', 'tmp', 'finalize', 'drafts']
/** Git-exclude entries for launcher operational scratch. Shared by create and
 *  refresh so the two never drift. */
const STEWARD_EXCLUDES = [
  '.alice/steward/state.json',
  '.alice/steward/locks/',
  '.alice/steward/supervisor.jsonl',
  '.alice/steward/tmp/',
  '.alice/steward/finalize/',
  '.alice/steward/drafts/',
  '.alice/steward/ledger/decisions.jsonl.lock',
  '.alice/steward/ledger/.decisions.jsonl.tmp-*',
]

const stewardReadme = `# Steward Workspace

This directory is the steward's structured trading context. A steward wake is
not a general coding request; it is a narrow trading decision envelope that must
end with one validated decision recorded for that wake.

## Files

- config.json: steward defaults, session pointer, account placeholder, and
  cost budget assumptions.
- context-manifest.json: generated by OpenAlice context injection after root
  instructions and skills are written.
- wakes/<wakeId>.json: one structured input envelope per wake.
- drafts/<wakeId>.json: where YOU write this wake's decision object, with your
  Write/Edit tool (issue #140). This is the ONLY file you write.
- ledger/decisions.jsonl: the committed decision log. You NEVER edit this file
  directly — the validator is its only supported writer. A direct edit is
  treated as corruption (the supervisor detects it as an integrity violation).
- validate-ledger.mjs: reads drafts/<wakeId>.json, strictly validates it,
  cross-checks that every already-completed wake still has its ledger entry, and
  is the COMMIT POINT: it atomically appends (or, for a same-wake pre-terminal
  correction, replaces in place) your entry in the ledger and publishes a
  finalization marker. The supervisor completes the wake only after that marker
  matches the committed entry. To correct before the wake completes, WRITE the
  draft again (a successful run removes it) and re-run the validator.
- finalize/: gitignored per-wake finalization markers. You do not edit these.
- tmp/: gitignored scratch space for --json-file payloads (order/commit/reject
  free-text fields written here via the Write tool, then passed to alice-uta
  by path — never embedded in a Bash argument).

## First action on wake

Read the wake file named by the injected wake message, then run the fixed UTA
checklist: account, positions, open orders, risk, market, and history. Decide
no_trade, propose_trade, or blocked. Write your decision object to
drafts/<wakeId>.json (Write/Edit only), then run
\`node .alice/steward/validate-ledger.mjs <wakeId>\` to commit and finalize it.

Do not inspect OpenAlice source code. Do not call push. Never edit
decisions.jsonl directly. Do not end a wake without a validated decision.
`

const validateLedger = `#!/usr/bin/env node
const wakeId = process.argv[2]
if (!wakeId) fail('usage: node .alice/steward/validate-ledger.mjs <wakeId>')

const fs = await import('node:fs/promises')

const STEWARD = '.alice/steward'
const ledgerPath = STEWARD + '/ledger/decisions.jsonl'
const lockPath = ledgerPath + '.lock'
const draftPath = STEWARD + '/drafts/' + encodeURIComponent(wakeId) + '.json'
const wakePath = STEWARD + '/wakes/' + encodeURIComponent(wakeId) + '.json'
const finalizeDir = STEWARD + '/finalize'

// ---- external binding: active, non-terminal wake record (issue #139) ----
const terminalStatuses = ['done', 'blocked', 'error', 'timeout', 'stuck']
let wakeRecord
try {
  wakeRecord = JSON.parse(await fs.readFile(wakePath, 'utf8'))
} catch (err) {
  if (err && err.code === 'ENOENT') fail('no active posted wake "' + wakeId + '" (no wake record under .alice/steward/wakes/) -- validate with the exact wakeId from the wake message; do not invent or copy a prior wake id')
  fail('cannot read wake record for "' + wakeId + '": ' + err.message)
}
if (wakeRecord && terminalStatuses.includes(wakeRecord.status)) fail('wake "' + wakeId + '" is already ' + wakeRecord.status + '; a completed wake cannot be re-finalized -- finalize only the active posted wake')

// ---- read the draft (issue #140: the agent writes the draft, never decisions.jsonl) ----
let draftRaw
try {
  draftRaw = await fs.readFile(draftPath, 'utf8')
} catch (err) {
  if (err && err.code === 'ENOENT') fail('no draft at ' + draftPath + ' -- write your decision object there with your Write/Edit tool, then re-run; never edit decisions.jsonl directly')
  fail('cannot read draft for "' + wakeId + '": ' + err.message)
}
let entry
try {
  entry = JSON.parse(draftRaw)
} catch (err) {
  fail('draft ' + draftPath + ' is not valid JSON: ' + err.message)
}
if (!entry || typeof entry !== 'object' || Array.isArray(entry)) fail('draft must be a single JSON object')
if (entry.wakeId !== wakeId) fail('draft top-level wakeId (' + JSON.stringify(entry.wakeId) + ') must equal the wake you are finalizing (' + wakeId + ')')

// ---- strict v2 schema (issue #125) + evidence self-reference (issue #139) ----
const requiredTopLevel = ['version', 'wakeId', 'at', 'accountId', 'decision', 'status', 'completion', 'checklist', 'thesis', 'actions', 'pendingHash', 'invalidation', 'cost']
const requiredChecklist = ['account', 'positions', 'orders', 'risk', 'market', 'history']
const requiredCost = ['model', 'inputTokens', 'outputTokens', 'modelCostUsd', 'allocatedServerCostUsd', 'tradingFeesUsd', 'estimatedSlippageUsd', 'totalEstimatedCostUsd']
const actionKinds = ['order_place', 'order_commit', 'order_modify', 'order_cancel', 'position_close', 'git_reject']
const actionOutcomes = ['executed', 'awaiting_approval', 'policy_denied', 'failed']

const missing = requiredTopLevel.filter((key) => !(key in entry))
if (missing.length) fail('draft is missing top-level field(s): ' + missing.join(', '))
if (entry.version !== 2) fail('draft version must be 2')
if (!['no_trade', 'propose_trade', 'blocked'].includes(entry.decision)) fail('draft has invalid decision')
if (!['done', 'blocked', 'error'].includes(entry.status)) fail('draft has invalid status')
if (!entry.completion || typeof entry.completion !== 'object' || Array.isArray(entry.completion)) fail('draft completion must be an object')
if (typeof entry.completion.reason !== 'string' || !entry.completion.reason.trim()) fail('draft completion.reason is required')
if (!Array.isArray(entry.completion.evidenceRefs) || entry.completion.evidenceRefs.length === 0) fail('draft completion.evidenceRefs must be a non-empty array')
const evWakeRefs = entry.completion.evidenceRefs.filter((r) => typeof r === 'string' && r.indexOf('wake:') === 0).map((r) => r.slice(5))
if (evWakeRefs.indexOf(entry.wakeId) === -1) fail('draft completion.evidenceRefs must include the self-reference "wake:' + entry.wakeId + '" matching the top-level wakeId')
for (let r = 0; r < evWakeRefs.length; r++) {
  if (evWakeRefs[r] !== entry.wakeId) fail('draft completion.evidenceRefs references a different wake (' + evWakeRefs[r] + ') than the top-level wakeId (' + entry.wakeId + '); a copied or contradictory wake id is invalid -- fix the top-level wakeId to match the posted wake')
}
if (!entry.checklist || typeof entry.checklist !== 'object' || Array.isArray(entry.checklist)) fail('draft checklist must be a TOP-LEVEL object, not nested inside completion')
const missingChecklist = requiredChecklist.filter((key) => typeof entry.checklist[key] !== 'string' || !entry.checklist[key])
if (missingChecklist.length) fail('draft checklist is missing field(s): ' + missingChecklist.join(', '))
if (!Array.isArray(entry.actions)) fail('draft actions must be an array')
let anyExecuted = false
for (let a = 0; a < entry.actions.length; a++) {
  const action = entry.actions[a]
  const where = 'draft actions[' + a + ']'
  if (!action || typeof action !== 'object' || Array.isArray(action)) fail(where + ' must be an object -- free-text action strings are rejected at v2')
  if (!actionKinds.includes(action.kind)) fail(where + ' has invalid kind: ' + JSON.stringify(action.kind) + '; expected one of ' + actionKinds.join(', '))
  if (!action.params || typeof action.params !== 'object' || Array.isArray(action.params)) fail(where + ' params must be an object summary')
  if (!actionOutcomes.includes(action.outcome)) fail(where + ' has invalid outcome: ' + JSON.stringify(action.outcome) + '; expected one of ' + actionOutcomes.join(', '))
  if (action.kind !== 'git_reject' && (typeof action.aliceId !== 'string' || !action.aliceId)) fail(where + ' requires a non-empty aliceId')
  if (action.outcome === 'policy_denied' && (!Array.isArray(action.violations) || action.violations.length === 0)) fail(where + ' is policy_denied and must record non-empty violations')
  if (action.outcome === 'executed' && action.kind !== 'git_reject' && (typeof action.commitHash !== 'string' || !action.commitHash)) fail(where + ' is executed and must record its commitHash')
  if (action.outcome === 'executed') anyExecuted = true
}
if (entry.pendingHash !== null && typeof entry.pendingHash !== 'string') fail('draft pendingHash must be string or null')
if (anyExecuted && entry.pendingHash !== null) fail('draft pendingHash must be null once an action has outcome "executed" (put the commit hash in actions[].commitHash)')
if (!entry.cost || typeof entry.cost !== 'object' || Array.isArray(entry.cost)) fail('draft cost must be an object')
const missingCost = requiredCost.filter((key) => !(key in entry.cost))
if (missingCost.length) fail('draft cost is missing field(s): ' + missingCost.join(', '))

// ---- canonical fingerprint (mirrors src/workspaces/steward/ledger-receipt.ts) ----
const { createHash } = await import('node:crypto')
const LEDGER_SEMANTIC_KEYS = ['version', 'wakeId', 'at', 'accountId', 'decision', 'status', 'context', 'completion', 'checklist', 'thesis', 'actions', 'pendingHash', 'invalidation', 'cost']
function canonicalize(value) {
  if (Array.isArray(value)) return value.map(canonicalize)
  if (value && typeof value === 'object') {
    const out = {}
    for (const key of Object.keys(value).sort()) out[key] = canonicalize(value[key])
    return out
  }
  return value
}
function semanticProjection(obj) {
  const source = obj && typeof obj === 'object' ? obj : {}
  const out = {}
  for (const key of LEDGER_SEMANTIC_KEYS) if (key in source) out[key] = source[key]
  return out
}
function ledgerFingerprint(obj) {
  return createHash('sha256').update(JSON.stringify(canonicalize(semanticProjection(obj)))).digest('hex')
}

// ---- cross-process lock + atomic write (mirrors src/workspaces/steward/ledger-writer.ts) ----
const LOCK_TTL_MS = 30000
let tmpCounter = 0
function sleep(ms) { return new Promise((r) => setTimeout(r, ms)) }
function isCode(err, codes) { return err && typeof err === 'object' && codes.indexOf(err.code) !== -1 }
async function reclaimIfStale() {
  let info = null
  try { info = JSON.parse(await fs.readFile(lockPath, 'utf8')) } catch { return }
  if (!info || typeof info.at !== 'number' || Date.now() - info.at <= LOCK_TTL_MS) return
  const aside = lockPath + '.stale-' + process.pid + '-' + (tmpCounter++)
  await fs.rename(lockPath, aside).catch(() => {})
  await fs.rm(aside, { force: true }).catch(() => {})
}
async function acquireLock() {
  const token = process.pid + '-' + Date.now() + '-' + (tmpCounter++)
  // 200 attempts x up-to-200ms outlast the 30000ms stale TTL (parity with
  // src/workspaces/steward/ledger-writer.ts).
  for (let attempt = 0; attempt < 200; attempt++) {
    let fh
    try {
      fh = await fs.open(lockPath, 'wx')
    } catch (err) {
      if (!isCode(err, ['EEXIST'])) fail('ledger lock error: ' + err.message)
      await reclaimIfStale()
      await sleep(Math.min(15 * (attempt + 1), 200))
      continue
    }
    try {
      await fh.writeFile(JSON.stringify({ pid: process.pid, token, at: Date.now() }))
      await fh.sync().catch(() => {})
    } finally {
      await fh.close()
    }
    return token
  }
  fail('could not acquire steward ledger lock ' + lockPath + ' within the acquire budget (a stale lock is auto-reclaimed after ' + LOCK_TTL_MS + 'ms; this is safe to retry)')
}
async function releaseLock(token) {
  try {
    const info = JSON.parse(await fs.readFile(lockPath, 'utf8'))
    if (info && info.token !== token) return
  } catch { return }
  await fs.rm(lockPath, { force: true }).catch(() => {})
}
async function renameWithRetry(from, to) {
  for (let attempt = 0; ; attempt++) {
    try { await fs.rename(from, to); return }
    catch (err) {
      if (attempt < 20 && isCode(err, ['EPERM', 'EACCES', 'EEXIST', 'EBUSY'])) { await sleep(25 * (attempt + 1)); continue }
      throw err
    }
  }
}
async function atomicWrite(target, content) {
  const slash = target.lastIndexOf('/')
  const dir = target.slice(0, slash)
  const base = target.slice(slash + 1)
  const tmp = dir + '/.' + base + '.tmp-' + process.pid + '-' + Date.now() + '-' + (tmpCounter++)
  const fh = await fs.open(tmp, 'w')
  try { await fh.writeFile(content, 'utf8'); await fh.sync() } finally { await fh.close() }
  try { await renameWithRetry(tmp, target) }
  catch (err) { await fs.rm(tmp, { force: true }).catch(() => {}); fail('atomic write failed for ' + target + ': ' + err.message) }
  try { const dh = await fs.open(dir, 'r'); await dh.sync().catch(() => {}); await dh.close() } catch {}
}

// ---- commit under the lock: cross-check prior terminals, upsert this wake's ----
// ---- line (append or in-place replace), atomic write; preserve other lines ----
const token = await acquireLock()
let committedLine
try {
  // Re-read the active wake record UNDER the lock: the supervisor may have
  // terminalized this wake between our first binding check and now. If it is
  // terminal, do not write the ledger or a marker (avoids a post-terminal
  // rewrite racing the supervisor).
  let recheck
  try { recheck = JSON.parse(await fs.readFile(wakePath, 'utf8')) } catch (err) { if (isCode(err, ['ENOENT'])) fail('wake record for "' + wakeId + '" vanished before commit'); fail('cannot re-read wake record for "' + wakeId + '": ' + err.message) }
  if (recheck && terminalStatuses.includes(recheck.status)) fail('wake "' + wakeId + '" became ' + recheck.status + ' before commit; not re-finalizing a completed wake')
  let raw = ''
  try { raw = await fs.readFile(ledgerPath, 'utf8') } catch (err) { if (!isCode(err, ['ENOENT'])) fail('cannot read ' + ledgerPath + ': ' + err.message) }
  const rawLines = raw.split('\\n')
  const meaningful = []
  for (let i = 0; i < rawLines.length; i++) { if (rawLines[i].trim().length > 0) meaningful.push(rawLines[i]) }

  const firstWins = new Map()
  for (let i = 0; i < meaningful.length; i++) {
    let p; try { p = JSON.parse(meaningful[i]) } catch { continue }
    if (p && typeof p === 'object' && typeof p.wakeId === 'string' && !firstWins.has(p.wakeId)) firstWins.set(p.wakeId, p)
  }
  // Issue #134 cross-check: every DISPATCHED terminal wake record must still
  // have its first-wins entry (and matching receipt fingerprint). A prior
  // integrity failure blocks this commit -> no ledger change, no marker.
  const wakesDir = STEWARD + '/wakes'
  let wakeFiles = []
  try { wakeFiles = (await fs.readdir(wakesDir)).filter((n) => n.endsWith('.json')) } catch (err) { if (!isCode(err, ['ENOENT'])) fail('cannot read ' + wakesDir + ': ' + err.message) }
  const terminalBacked = ['done', 'blocked', 'error']
  for (const name of wakeFiles) {
    let rec; try { rec = JSON.parse(await fs.readFile(wakesDir + '/' + name, 'utf8')) } catch (err) { fail('wake record ' + name + ' is invalid JSON: ' + err.message) }
    if (!rec || typeof rec !== 'object' || !terminalBacked.includes(rec.status)) continue
    if (!rec.injectedAt && !rec.ledgerReceipt) continue
    const priorEntry = firstWins.get(rec.wakeId)
    if (!priorEntry) fail('terminal wake ' + rec.wakeId + ' (status ' + rec.status + ') has no ledger entry -- an earlier completed decision disappeared from ' + ledgerPath)
    if (rec.ledgerReceipt && typeof rec.ledgerReceipt.fingerprint === 'string') {
      if (ledgerFingerprint(priorEntry) !== rec.ledgerReceipt.fingerprint) fail('terminal wake ' + rec.wakeId + ' ledger entry changed since it was recorded (fingerprint mismatch) -- ledger history was mutated in place')
    }
  }

  const newLine = JSON.stringify(entry)
  const matchIdx = []
  for (let i = 0; i < meaningful.length; i++) {
    let p; try { p = JSON.parse(meaningful[i]) } catch { continue }
    if (p && p.wakeId === wakeId) matchIdx.push(i)
  }
  if (matchIdx.length > 1) fail('ledger already has ' + matchIdx.length + ' entries for wake ' + wakeId + ' (lines ' + matchIdx.map((i) => i + 1).join(', ') + '); exactly one is allowed (first-wins)')
  const outLines = meaningful.slice()
  if (matchIdx.length === 1) outLines[matchIdx[0]] = newLine
  else outLines.push(newLine)
  committedLine = matchIdx.length === 1 ? (matchIdx[0] + 1) : outLines.length

  await atomicWrite(ledgerPath, outLines.join('\\n') + '\\n')
} finally {
  await releaseLock(token)
}

// ---- finalize marker (only after a successful commit; issue #136) ----
await fs.mkdir(finalizeDir, { recursive: true })
const markerPath = finalizeDir + '/' + encodeURIComponent(wakeId) + '.json'
const marker = { version: 1, wakeId, fingerprint: ledgerFingerprint(entry), validatedAt: new Date().toISOString(), schemaVersion: entry.version }
await atomicWrite(markerPath, JSON.stringify(marker, null, 2) + '\\n')

// ---- clean up the draft on success (kept on any failure for correction) ----
await fs.rm(draftPath, { force: true }).catch(() => {})

console.log('ok: wake ' + wakeId + ' committed to ledger (line ' + committedLine + ') and finalization marker published')

function fail(message) {
  console.error('validate-ledger: ' + message)
  process.exit(1)
}
`

const config = {
  version: 1,
  agent: 'codex',
  sessionId: null,
  accountId: null,
  monthlyBudget: {
    modelUsd: 200,
    serverUsd: 50,
  },
  costPolicy: {
    warnAtPct: 80,
    blockAtPct: 100,
  },
}

const runtimeJson = `${JSON.stringify({ protocol: STEWARD_RUNTIME_PROTOCOL }, null, 2)}\n`

if (REFRESH_MODE) {
  // outDir is an EXISTING workspace directory.
  if (!existsSync(outDir)) {
    console.error(`refresh-runtime: workspace does not exist: ${outDir}`)
    process.exit(1)
  }
  const stewardRoot = join(outDir, '.alice', 'steward')
  for (const d of STEWARD_RUNTIME_DIRS) mkdirSync(join(stewardRoot, d), { recursive: true })
  // Launcher-owned operational files: atomic same-dir replace, skip if identical.
  // NEVER touch config.json, wakes/, ledger/decisions.jsonl, finalize/ markers,
  // or drafts/ — those are workspace/user content and are not migrated.
  writeLauncherOwnedFilesAtomic(stewardRoot)
  ensureGitExcludesIdempotent(outDir, STEWARD_EXCLUDES)
  console.log(`refreshed steward runtime at ${outDir}`)
} else {
  initWorkspaceDir(outDir)
  copyReadme(outDir)

  await git(['init', '-q'], outDir)
  setupGitExcludes(outDir, ...STEWARD_EXCLUDES)

  const stewardRoot = join(outDir, '.alice', 'steward')
  for (const d of STEWARD_RUNTIME_DIRS) mkdirSync(join(stewardRoot, d), { recursive: true })

  // Launcher-owned operational files (same constants the refresh path writes).
  writeFileSync(join(stewardRoot, 'README.md'), stewardReadme)
  writeFileSync(join(stewardRoot, 'validate-ledger.mjs'), validateLedger)
  writeFileSync(join(stewardRoot, 'runtime.json'), runtimeJson)
  // Fresh workspace user content.
  writeFileSync(join(stewardRoot, 'config.json'), `${JSON.stringify(config, null, 2)}\n`)
  writeFileSync(join(stewardRoot, 'wakes', '.gitkeep'), '')
  writeFileSync(join(stewardRoot, 'ledger', 'decisions.jsonl'), '')
  writeFileSync(join(stewardRoot, 'supervisor.jsonl'), '')

  console.log(`bootstrapped steward workspace '${tag}' at ${outDir}`)
}

/** Write the launcher-owned operational files with a same-dir atomic replace,
 *  skipping any file whose content already matches (issue #140 refresh). */
function writeLauncherOwnedFilesAtomic(stewardRoot) {
  atomicReplaceIfChanged(join(stewardRoot, 'validate-ledger.mjs'), validateLedger)
  atomicReplaceIfChanged(join(stewardRoot, 'README.md'), stewardReadme)
  atomicReplaceIfChanged(join(stewardRoot, 'runtime.json'), runtimeJson)
}

/** Atomic same-dir replace; returns false (no write) when content is unchanged. */
function atomicReplaceIfChanged(path, content) {
  let existing = null
  try { existing = readFileSync(path, 'utf8') } catch { /* missing */ }
  if (existing === content) return false
  const tmp = `${path}.tmp-${process.pid}-${Date.now()}`
  writeFileSync(tmp, content)
  renameSync(tmp, path)
  return true
}

/** Append only the exclude entries not already present (idempotent). No-op if
 *  the workspace has no git exclude file — refresh must never init a repo. */
function ensureGitExcludesIdempotent(workspaceDir, entries) {
  const excludePath = join(workspaceDir, '.git', 'info', 'exclude')
  if (!existsSync(excludePath)) return
  const existing = readFileSync(excludePath, 'utf8')
  const have = new Set(existing.split('\n').map((l) => l.trim()))
  const missing = entries.filter((e) => !have.has(e))
  if (missing.length === 0) return
  const prefix = existing.length > 0 && !existing.endsWith('\n') ? '\n' : ''
  appendFileSync(excludePath, `${prefix}${missing.join('\n')}\n`)
}
