/**
 * Bootstrap a steward workspace: a fresh git repo with the first persistent
 * trading-agent scaffold. Cross-platform Node, run by the Electron-bundled
 * Node and bundled git via `_common.mjs`.
 *
 * Context injection writes AGENTS.md / CLAUDE.md, CLI skills, and the final
 * context manifest after this script returns. This script owns only the
 * workspace-local steward file layout.
 *
 *   argv: process.argv[2] = tag, process.argv[3] = outDir
 *   env:  AQ_TEMPLATE_ROOT - abs path to this template's root
 */

import { mkdirSync, writeFileSync } from 'node:fs'
import { join } from 'node:path'
import { initWorkspaceDir, copyReadme, setupGitExcludes, git } from '../_common.mjs'

const tag = process.argv[2]
const outDir = process.argv[3]
if (!tag || !outDir) {
  console.error('usage: bootstrap.mjs <tag> <outDir>')
  process.exit(1)
}

const stewardReadme = `# Steward Workspace

This directory is the steward's structured trading context. A steward wake is
not a general coding request; it is a narrow trading decision envelope that must
end with one JSON line in ledger/decisions.jsonl.

## Files

- config.json: steward defaults, session pointer, account placeholder, and
  cost budget assumptions.
- context-manifest.json: generated by OpenAlice context injection after root
  instructions and skills are written.
- wakes/<wakeId>.json: one structured input envelope per wake.
- ledger/decisions.jsonl: one structured decision/completion marker per wake.

## First action on wake

Read the wake file named by the injected wake message, then run the fixed UTA
checklist: account, positions, open orders, risk, market, and history. Decide
no_trade, propose_trade, or blocked. Append exactly one ledger JSON object.

Do not inspect OpenAlice source code. Do not call push. Do not end a wake
without a ledger entry.
`

const config = {
  version: 1,
  agent: 'codex',
  sessionId: null,
  accountId: null,
  monthlyBudget: {
    modelUsd: 200,
    serverUsd: 50,
  },
  costPolicy: {
    warnAtPct: 80,
    blockAtPct: 100,
  },
}

initWorkspaceDir(outDir)
copyReadme(outDir)

await git(['init', '-q'], outDir)
setupGitExcludes(
  outDir,
  '.alice/steward/state.json',
  '.alice/steward/locks/',
  '.alice/steward/supervisor-status.json',
)

const stewardRoot = join(outDir, '.alice', 'steward')
mkdirSync(join(stewardRoot, 'wakes'), { recursive: true })
mkdirSync(join(stewardRoot, 'ledger'), { recursive: true })
mkdirSync(join(stewardRoot, 'locks'), { recursive: true })

writeFileSync(join(stewardRoot, 'README.md'), stewardReadme)
writeFileSync(join(stewardRoot, 'config.json'), `${JSON.stringify(config, null, 2)}\n`)
writeFileSync(join(stewardRoot, 'wakes', '.gitkeep'), '')
writeFileSync(join(stewardRoot, 'ledger', 'decisions.jsonl'), '')
writeFileSync(join(stewardRoot, 'supervisor.jsonl'), '')

console.log(`bootstrapped steward workspace '${tag}' at ${outDir}`)
